apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvprod002
  labels:
   nfs: server
spec:
  capacity:             # 指定 PV 容量
    storage: 10Gi
  volumeMode: Filesystem  # 卷模式，除了文件系统，还支持原始块，Filesystem／Block
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow-mongo      # 存储类名。指定类名的 PV 需要与指定类名的 PVC 绑定
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: 10.1.141.19
